# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YMDouYuZB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher'
    
    
  # Pods for YMDouYuZB
  target 'YMDouYuZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YMDouYuZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
